### ISSUE TITLE
user deploy scripts may be skipped or repeated

### ISSUE THREAD

**Issue by pyggie** [wighawag/buidler-deploy#1]
Hello, a few little issues I found with buidler-deploy version 0.1.9 with TypeScript.

* In src/utils/eth.js, two cases of "catch{}" should be changed to "catch(e) {}".

* The declared signature of DeploymentsExtension.run() has "tags?: string | string[]" but it only works for the string array. The problem is DeploymentsManager.ts line 266 "for (const tagToFind of tags) {  ", which does not distinguish the two types.

* In DeploymentsExtension.ts the recurseDependencies() function may add the same script twice. At line 294 after recursive call it doesn't re-test the condition scriptsRegisteredToRun which may have changed during the recursive call.

* If the user defines multiple deploy/xxx.ts scripts and these each define a function deploy() with the same function body, then only the first script will run. The reason is because recurseDependencies() uses the user deploy() function as an object key, and the Javascript engine treats identical function bodies as the same key.

**Comment by wighawag** [comment]
Thanks @pyggie for the report, I am going to investigate the issues as soon as I can

**Comment by wighawag** [comment]
I fixed all the issue in 0.1.11. Thanks you!
I did not know about js identical func body.
