### ISSUE TITLE
Consider removing `deployments` when the `clean` task is run

### ISSUE THREAD

**Issue by fvictorio** [wighawag/buidler-deploy#10]
I'm not sure if this makes sense, but it might? I kind of expected this to happen. I think this depends on how `deployments` is meant to be used. For example, is it meant to be committed? If it is, then the current behavior is ok. If not, maybe it should be removed when `clean` is executed.

**Comment by wighawag** [comment]
I never use the clean task, did not even remember it existed.
I personally commit the deployments folder so yes that's kind of how it is intended. So unless this is an important feature I woudl leave as is.

**Comment by fvictorio** [comment]
Oh, no, if they are meant to be committed (or even if it makes sense for some people to commit them), I think `clean` should not remove them. Thanks!
