### ISSUE TITLE
Sample script makes `node` fail for trivial scenario

### ISSUE THREAD

**Issue by fvictorio** [wighawag/buidler-deploy#11]
I created a very simple project with a contract `Foo` and a script based on the one shown in the README:

```javascript
module.exports = async ({getNamedAccounts, deployments}) => {
    const {deployIfDifferent, log} = deployments;
    const {deployer} = await getNamedAccounts();

    let contract = await deployments.get('Foo');

    if (!contract) {
        const deployResult = await deployIfDifferent([], "Foo",  {from: deployer, gas: 4000000}, "Foo");
        contract = await deployments.get('Foo');
        if(deployResult.newlyDeployed) {
            log(`Foo deployed at ${contract.address} for ${deployResult.receipt.gasUsed}`);
        }
    }
}
```

If I then run `buidler node` I get an error:

```
Error: No deployment found for: Foo
```

Am I doing something wrong, or is the script in the readme outdated?

**Comment by wighawag** [comment]
yes it is outdated, to check for existence, it should now be `deployemnts.getOrNull('Foo')`

**Comment by wighawag** [comment]
fixed with https://github.com/wighawag/buidler-deploy/commit/2233377ff56009c71c28b3b3744605e83f97068c
thanks for the report!
