### ISSUE TITLE
Add a typescript section to README

### ISSUE THREAD

**Issue by tuler** [wighawag/buidler-deploy#17]
I know the project already includes typings, which is great!
But I'm not very familiar with type extensions and I'm not sure how to add typing to deploy scripts.
It would be super helpful to have a typescript section to the README explaining what needs to be changed.

**Comment by wighawag** [comment]
Thanks @tuler for your issue, fix added via : https://github.com/wighawag/buidler-deploy/commit/b158e385fc9401f83a7a5655fd9d51ffd82c0deb

Planning to add documentation more but welcome any suggestion or PR that improves it
