### ISSUE TITLE
`buidler node` does not deploy contracts

### ISSUE THREAD

**Issue by tuler** [wighawag/buidler-deploy#19]
Documentation states that [buidler node automatically deploy contracts](https://github.com/wighawag/buidler-deploy#node).
That is not happening for me.
I don't know if I'm missing something.

I'm using the following dependencies (among others)

```json
    "@nomiclabs/buidler": "^1.3.8",
    "@nomiclabs/buidler-ethers": "^2.0.0",
    "@nomiclabs/buidler-waffle": "^2.0.0",
    "@nodefactory/buidler-typechain": "^0.2.0",
    "buidler-deploy": "^0.4.13",
```

**Comment by wighawag** [comment]
I assume you have deploy script in the deploy folder that deploy contracts ?
If so, could you post one to see if there is any issues with it

**Comment by tuler** [comment]
Yes, I have two scripts: `deploy/01_libs.ts` and `02_proxy_manager.ts`.

```typescript
import {
    BuidlerRuntimeEnvironment,
    DeployFunction
} from "@nomiclabs/buidler/types";

const func: DeployFunction = async (bre: BuidlerRuntimeEnvironment) => {
    const { deployments, getNamedAccounts } = bre;
    const { deploy } = deployments;
    const a = await getNamedAccounts();
    const { deployer } = await getNamedAccounts();

    await deploy("BitsManipulationLibrary", { from: deployer });
    await deploy("Merkle", { from: deployer });
    await deploy("CartesiMath", { from: deployer });
};

export default func;
export const tags = ['Libs'];
```

```typescript [title=02_proxy_manager.ts]
import {
    BuidlerRuntimeEnvironment,
    DeployFunction
} from "@nomiclabs/buidler/types";

const func: DeployFunction = async (bre: BuidlerRuntimeEnvironment) => {
    const { deployments, getNamedAccounts } = bre;
    const { deploy } = deployments;
    const a = await getNamedAccounts();
    const { deployer } = await getNamedAccounts();

    await deploy("ProxyManager", { from: deployer });
};

export default func;
export const tags = ['ProxyManager'];
```

When I run `bundler node` it just prints this to the console:

```
(node:61910) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61910) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
All contracts have already been compiled, skipping compilation.
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/
```

I don't know if it should print the deployment transactions, the ones that appear when I manually run `buidler deploy --network localhost`:

```
eth_sendTransaction
  Contract deployment: BitsManipulationLibrary
  Contract address:    0x7c2c195cd6d34b8f845992d380aadb2730bb9c6f
  Transaction:         0x9ad70c7c5d554d0b32ea0da98ccd61bdf0f56f30d0b637e261febd3b99cdfeff
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  Value:               0 ETH
  Gas used:            199076 of 995380
  Block #1:            0xf822db574cde15fcf7b36624187125648e0dcef3474283bdc11acd437a9fdc0f

eth_sendTransaction
  Contract deployment: Merkle
  Contract address:    0x8858eeb3dfffa017d4bce9801d340d36cf895ccf
  Transaction:         0xe397838fc64c9e3cf192a5581f19d414c372b0e1e8f7d7ab253e0845802e0d77
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  Value:               0 ETH
  Gas used:            71933 of 359665
  Block #2:            0xd5aa6e376e13a8c78596de0a2393960106a1c1df81b8ede2c018d63b51082ba9

eth_sendTransaction
  Contract deployment: CartesiMath
  Contract address:    0x0078371bdede8aac7debfff451b74c5edb385af7
  Transaction:         0x166d371e80d3272414fc6e078bcb1e22f9c232b77afb517755cd9d97262f1eba
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  Value:               0 ETH
  Gas used:            2793570 of 9024999
  Block #3:            0x1f61a085085f03ce95b9b3bd6f6712941fed5e24056d1cc2b0cc263bfaa2cabd

eth_sendTransaction
  Contract deployment: ProxyManager
  Contract address:    0xf4e77e5da47ac3125140c470c71cbca77b5c638c
  Transaction:         0x3910eb8e72aaa6f3c3759a5b3a74e2a3475245f90a50836a2c6919fdb1b626cf
  From:                0xc783df8a850f42e7f7e57013759c285caa701eb6
  Value:               0 ETH
  Gas used:            954958 of 4774790
  Block #4:            0x4de5dc1cf12de0441877e3726f85d75c9e9240198cca1e2874f60c48ebcc9dbc

```

**Comment by wighawag** [comment]
thanks for the info. 

so `buidler node` does not log request like ganache

buidler-deploy have on the other hand some builtin log capability:
if you want to log the deployment you can add `log: true` to the option

so like `await deploy("BitsManipulationLibrary", { from: deployer, log: true });`

So maybe your contract are actually deployed, you are just not seeing it

You can also check that by triggering `buidler console --network localhost` (after `buidler node` is invoked and get your deployment via `await deployments.get("BitsManipulationLibrary")`

**Comment by tuler** [comment]
The deployment lines above are not actually from `ganache`, they are from `buidlerevm`.
But the `log: true` worked, and it prints the following after starting the node:
```
"BitsManipulationLibrary" deployed at 0x7c2C195CD6D34B8F845992d380aADB2730bB9C6F with 199076 gas
"Merkle" deployed at 0x8858eeB3DfffA017D4BCE9801D340D36Cf895CCf with 71933 gas
"CartesiMath" deployed at 0x0078371BDeDE8aAc7DeBfFf451B74c5EDB385Af7 with 2793570 gas
"ProxyManager" deployed at 0xf4e77E5Da47AC3125140c470c71cBca77B5c638c with 954958 gas
```

Something is weird on my end then. When I try to interact with the contract through my web application (metamask, ethers, react, etc) I get a strange error:

```
eth_call
  WARNING: Calling an account which is not a contract
  From: 0x18930e8a66a1dbe21d00581216789aab7460afd0
  To:   0xf4e77e5da47ac3125140c470c71cbca77b5c638c
```

Guess I need to investigate deeper.

**Comment by wighawag** [comment]
hmm, this indicate that the contract are deployed to another network
Are you using ganache and buidlerevm at the same time ?

**Comment by tuler** [comment]
No, no ganache. Just `buidlerevm`.

**Comment by tuler** [comment]
I spent some hours investigating but don't understand why it doesn't work.
The fact is that it only works after I manually deploy with `buidler deploy --network localhost`, where `localhost` is the `buidlerevm` running by `buidler node`, as far as I understand. (Or is it a ganache??)

The error above becomes:
```
eth_call
  Contract call:       ProxyManager#getUser
  From:                0x18930e8a66a1dbe21d00581216789aab7460afd0
  To:                  0xf4e77e5da47ac3125140c470c71cbca77b5c638c
```

**Comment by wighawag** [comment]
hmm, yes that's weird indeed. going to look if there is any recent update that could cause this.

You right, when you execute `buidler node` it is running the buidlerevm, not ganache

**Comment by tuler** [comment]
I noticed that no blocks are mined after the node is up and deploy is “executed”. Block number is still 0.
Is this expected?

**Comment by tuler** [comment]
I’m reading the code and I don’t quite understand because it looks like the deploy is done while the buidlerevm is not even created.

https://github.com/wighawag/buidler-deploy/blob/06ec0ae341f24736fc4e49a30aa9c229229409c6/src/index.ts#L267

**Comment by wighawag** [comment]
Ok, found the issue. not sure when it happened, but I recently changed the order of creation in `builder node`
I am bit surprised it was not caught on, so maybe it is also related to a change in buidler too.

I have a fix, going to make it hopefully today

What is happening is that 2 provider are created and the deployment is made on the one disconnected from the server
so while all deployment succeed they are never accessible via localhost.

the fix is a workaround that requires me to bypass readonly variable in builder. I thinlk buidler should keep the `node` provider as the main bre network.provider.

**Comment by wighawag** [comment]
Also, `buidler --network localhost console ` will not detect the deployments as `buidler node` save deployment for network named `buidlerevem` 
this is unfortunate for console user. I could maybe ensure that when `buidler node` is run it is considered as `localhost` for saving deployments at least, but this might be confusing

**Comment by wighawag** [comment]
fixed in 0.4.14
let me know if you still encounter issues

I made `buidler node` to have its name `localhost` so the deployments are saved as a `localhost` network. it actually make sense since in any case to access it you need use `--network localhost`

**Comment by tuler** [comment]
It works now! Thanks.

I think saving as `localhost` makes sense.
What is the meaning of having `--export`, with a different format (single file will all contracts), when you already have deployments directory? Will it be removed, or is there a use case?

**Comment by wighawag** [comment]
Thanks you for the report!

The export is meant to be used by webapp as a lightweight version that contains all contract for te network. I use it myself for several project and it is very handy as you can make it go in the webapp source folder in one command

The directory version contains a lot more info that is not necessary for webapp (at least most)

There is also an `--export-all` version that export all contract across all saved netwotk. It is useful in some case where an app want to work across multiple network at the same time

**Comment by tuler** [comment]
Cool, thanks.
What I do is to `yarn link` the webapp project and the solidity project.
And I bundle the deployments with the npm package, I mean testnet deployments, not `localhost`.

**Comment by tuler** [comment]
By the way I'm still to see how your deploy can work with multi npm project dependencies. We have around 6 separate projects that depend on each other.
