### ISSUE TITLE
Write task with external deployments and artifacts loaded

### ISSUE THREAD

**Issue by tuler** [wighawag/buidler-deploy#43]
I'm trying to [write a buidler task](https://buidler.dev/guides/create-task.html) but when my task is executed I try to get `bre.deployments.all();` but it's empty.
My `builder.config.ts` has a bunch of `external` configs.

I'm not sure if this was supposed to work though.

**Comment by wighawag** [comment]
Hi @tuler for the task to have the deployments available,
 either the deployment json files have to exist in the corresponding `deployments` folder (in which case you get already deployed contract)
or the task has to call the `deploy` task. (`bre.run("deploy")`)

**Comment by tuler** [comment]
I'm talking about bringing external deployments from npm packages.
Should they already be available at `bre.deployments.all()`?

**Comment by wighawag** [comment]
yes, these should be available (like for the deployments folder) assuming you are on the equivalent network
If this does not work, I would need more details, ideally a reproducible repo to figure out the problem

**Comment by tuler** [comment]
I just tested it again, and it works fine!
Sorry for the noise.
