### ISSUE TITLE
`saveDeployment: false` is ignored

### ISSUE THREAD

**Issue by vporton** [wighawag/buidler-deploy#46]
`saveDeployment: false` is ignored by Buidler Deploy 0.6.0-beta.16.

I have

```
    ganache: {
      gasLimit: 6000000000,
      defaultBalanceEther: 100,
      url: "http://localhost:8545",
      live: false,
      saveDeployment: false,
    },
```
but
```sh
npx buidler deploy --network ganache
```
does create files in `deployments/ganache/`.

**Comment by wighawag** [comment]
Thanks @vporton for reporting. I am going to have a look later this week hopefully

**Comment by wighawag** [comment]
it seems to be a typo, can you try with `saveDeployments: false`

**Comment by wighawag** [comment]
I need to update the doc though

**Comment by wighawag** [comment]
doc updated. let me know if this does not resolve the issue
I also remove the folder creating when saveDeployments is false in latest 0.6-beta
Note that if you are on 0.5, 0.6 introduce breaking changes that are unfortunately not documented much, except on the README
