### ISSUE TITLE
Consider renaming deployIfDifferent to deploy

### ISSUE THREAD

**Issue by adrianmcli** [wighawag/buidler-deploy#6]
This is an issue of ergonomics, and I feel that a simple `deploy()` function is more friendly to new users than `deployIfDifferent`. It also makes the code a lot easier to read and skim over.

Ideally, `deploy` should be idempotent anyway so you can make the default behaviour of `deploy` to skip deployment if nothing has changed. But in case people actually want to make sure deployment is happening every time, it can be possible to add an option to the options object for this:

```js
const deployOpts = {
  skipIfNoChange: false // true by default
}
```

I'm open to opposing thoughts, just wanted to provide an observation.

**Comment by wighawag** [comment]
Yes that make sense. If you name your deployment the same and nothing changed, this is highly probable that you do not want to redeploy.

**Comment by adrianmcli** [comment]
Yeah let's blend this into #7
