### ISSUE TITLE
Ignore hidden files

### ISSUE THREAD

**Issue by fvictorio** [wighawag/buidler-deploy#9]
Ignore files that start with `.` when reading all the files inside the `deploy` directory.

This was an issue for me because vim saves swap files next to the files you are editing, and so `buidler-deploy` tries to read them, which of course fails.

**Comment by wighawag** [comment]
Ok, yes sounds good, going to adf that

**Comment by wighawag** [comment]
fixed in: https://github.com/wighawag/buidler-deploy/commit/2233377ff56009c71c28b3b3744605e83f97068c (0.4.6)
